.bd B 3
.TH libinfo2000 1 "Sep 27, 2010" "TI Tools" "TI Code Generation Tools"
.SH NAME
libinfo2000 - Library Information Archiver
.SH SYNOPSIS
.B libinfo2000
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Builds an archive of information about available libraries.
This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2010, Texas Instruments, Inc.
