.bd B 3
.TH ilk2000 1 "Sep 27, 2010" "TI Tools" "TI Code Generation Tools"
.SH NAME
ilk2000 - Ifile Linker
.SH SYNOPSIS
.B ilk2000
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Links multiple input intermediate files into one output file.  Used for program-level compilation.
.SH OPTIONS
The following options are accepted by this tool:
.SS Options:
.SS
.TP
-h
Print a help message that includes usage and option information.
.SH EXIT STATUS
The following error values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
Unsuccessful completion; an error occured.
.PD
.SH COPYRIGHT
.TP
Copyright (c) 2010, Texas Instruments, Inc.
